### ISSUE TITLE
Unable to authenticate Grafana using JWT

### ISSUE THREAD

**Issue by ramzcode** [pomerium/pomerium-helm#242] opened 2022-01-03 06:37 UTC
using the latest version of Pomerium Helm and grafana(prometheus comunity stack).

authentication redirection not working and it says 

{
  "message": "invalid API key"
}

**Comment by travisgroth** [comment] 2022-01-04 15:09
Closing this as a dupe of https://github.com/pomerium/pomerium/issues/2887.

This does not sound helm specific.

**Closed by travisgroth** 2022-01-04 15:09 UTC
